### ISSUE TITLE
Make add-rdf fails

### ISSUE THREAD

**Issue by cordawyn** [dice-group/docker-halyard#4]
Hello!

I deployed a standalone Halyard, which seemed to work fine. But as I proceeded with "make add-rdf", it failed with the following error message:
```
...
docker run -it --rm --network dockerhalyard_default --env-file hadoop.env --env-file hbase.env dicegroup/halyard-sdk:master bulkload /foaf.rdf /tmp halyardtable
Unable to find image 'dicegroup/halyard-sdk:master' locally
docker: Error response from daemon: manifest for dicegroup/halyard-sdk:master not found.
```
Do I have to pre-build "halyard-sdk" myself?

**Comment by earthquakesan** [comment]
@cordawyn hi!

yes, you need to prebuild it. You can use `make build`.

**Comment by cordawyn** [comment]
That worked for me. Thank you!
